### ISSUE TITLE
Candidate Release Comments (Reviews Accepted)

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-evolution#184]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about **Reviews Accepted**

GitHub location: https://github.com/chaoss/wg-evolution/blob/master/metrics/Reviews_Accepted.md

Release candidate: https://chaoss.community/metric-reviews-accepted

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

**Important Dates**

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by foundjem** [comment]
look good to me

**Comment by jgbarah** [comment]
> Looks good to me, but this seems a duplicate metric.

Which one would be duplicating?

**Comment by germonprez** [comment]
@foundjem what is this duplicating?

**Comment by germonprez** [comment]
Ah! I see the duplicate. @klumb, in the webpage candidate list, Reviews Accepted is listed twice. Both link back to this issue.

**Comment by klumb** [comment]
It is listed twice because it informs two code development goals - activity and efficiency. We are presenting the metrics in the goal/question/metric format. Which means that any individual metric that informs multiple questions or goals could be presented multiple times. Additionally, if a metric is identified by multiple workgroups it could be presented in different tables. This was discussed briefly in one of the calls. In future releases, there is the possibility that single metrics could be presented many times. Some metrics inform many different goals and questions. At some point, the replication in the way the data is presented will need to be addressed for future releases. Per the previous call, it was decided that we should present them in this fashion despite the repetition as there was only one candidate metric affected.

**Comment by klumb** [comment]
However, I should note that the detail page it self is not duplicated and the issue links go the same place **so work on the metric is not being duplicated** it is only being presented in different places according to the goal/question/metic format.

**Comment by foundjem** [comment]
@klumb Thanks for the detail explanation, sounds good to me and clearer.

**Comment by jgbarah** [comment]
@klumb @germonprez @foundjem thanks!

**Comment by germonprez** [comment]
Resolved.
