### ISSUE TITLE
Release Notes (evolution)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-evolution#301]
Please leave comments and notes here to help construct the release notes document.

**Comment by ccarterlandis** [comment]
To include here (brief):
1. Changes in existing metrics
2. New metrics added

**Comment by germonprez** [comment]
@ccarterlandis could you update the release notes to include: 

- New metrics
- Changes to the focus areas (what is the new structure)? 
- If there are any major changes to the metrics.

**Comment by ccarterlandis** [comment]
# Release Notes

## New Metrics
- Issue Age
- Issue Response Time
- Issue Resolution Duration
- New Contributors Closing Issues

## Updated Focus Areas
For this release, we refactored the "Code Development" focus area into 3 separate focus areas:

	1. Code Development Activity
	2. Code Development Efficiency
	3. Code Development Process Quality

This change was made in order to more closely align with other working groups: rather than having one broad focus area with multiple subsections, we decided our intent would be better communicated by making each of these subsections into their own focus areas.
We kept the other 2 focus areas (Issue Resolution and Community Growth) the same.

## Major Metric Changes

No major changes were made to already existing metrics.

**Comment by germonprez** [comment]
Right on. Thanks.
