### ISSUE TITLE
Add new Metrics about branch lifecycle

### ISSUE THREAD

**Issue by king-gao** [chaoss/wg-evolution#368]
In my opinion, there are some  branch indicators are metrics for community healthy.

The branch lifecycle managment  reflect the community is active,the maintainer is concern the develop branch is merge into master branch,and after merge the develop branch should be deleted , the branch list is clear for anyone to understand the status of branch.

we can metrics how many branchs are still on the branch list have already been merged and not deleted.

**Comment by sgoggins** [comment]
King, 

Are we wanting to keep a list of branches at a point in time, and show delta's related to: 
1. branches deleted between t1 and t2
2. branches added between t1 and t2
3. total branches along t1, t2, tn .... ?

**Comment by king-gao** [comment]
Hi Sean, I agree with you 👍 .
others metrics for example : 

- How many branches have been merged but not deleted? 

- How long branch have been merged and not deleted?

- How many branches have been open more than XXX days?

- etc.
these are interesting metrics .

**Comment by sgoggins** [comment]
@king-gao : When you ask this question: 

"How many branches have been open more than XXX days?"

I think you are asking about "branch on an open pull request?"

**Comment by king-gao** [comment]
@sgoggins yes ,  If the PRs were been merged , shall we need to delete them in the public repo?

like the picture below , there are many branchs. why we are not delete them?

<img width="193" alt="20201010-164600(eSpace)" src="https://user-images.githubusercontent.com/58930496/95650754-1ab32200-0b18-11eb-80a5-d0ca3c309c9e.png">

**Comment by sgoggins** [comment]
We discussed this during the call for Evolution WG on 10/21 -- (Also notes from the Asia Pacific Call)

Examining the lifecycle of a branch
 - Branch deletion? 
 - Branch dormancy? 

What is the indicator of branch “death”. For example, if a branch has the word “patch” in a name, then it is likely a dormant branch. Especially if it had never been involved since the changes in the branch were merged. 

It seems we need to include both branch dormancy and branch deletion as indicators of a branch lifecycle. 

What are the differences between how branches are managed in GitLab, BitBucket and GitHub? This is something to consider during the building of this metric. 

To understand the local lifecycle, we would technically (literally, technically) have to cull that information from the git log. 

Platforms don’t keep track of local branch changes, but the git log does.

**Comment by ElizabethN** [comment]
Notes from the Asia Pacific Call: 
Open Issue discussion: Open branch lifecycle: https://github.com/chaoss/wg-evolution/issues/368 

What do we do with branches that are not needed anymore? 

Question: How do we know if a branch is not needed anymore? 

Can we have a metrics focused on telling us how many branches have not been active in the last X months? 

List of those branches 

How many branches have been opened for more than X days 

How many branches have been merged and are still open upstream 

This would be useful to know in order to clean the house, delete branches, etc.

**Comment by sgoggins** [comment]
This metric is now released: https://chaoss.community/metric-branch-lifecycle/
