### ISSUE TITLE
Use case: Characterize a bug reporter's past success at effectively reporting bugs.

### ISSUE THREAD

**Issue by kfogel** [chaoss/wg-evolution#61]
This grows out of discussion in issue #48:

* **Use Case:** If I knew that a particular bug reporter had a tendency to report bugs that resulted in associated bug fixes that were successfully merged, with the ticket closed as "FIXED" (or whatever the equivalent state is in that tracker), then when that person reported a bug in my project, I might pay attention more quickly.

Hmm.  You know, I think it might actually be that simple.  While there are a lot of complicated knobs and dials we could add -- about response time, length of conversation (number of turnarounds) in the ticket, etc -- but it would be simplest just to start with: "Does this person have a tendency to report bugs that get closed with a fix?"

**Comment by jgbarah** [comment]
Let me suggest a goal, based on your description: "Find out bug reporters whose past bug reports were successfully fixed".

If you agree on this goal, questions could be:

* To which extent past bug reports by this person were fixed?

I think this would be the main question.

* How many bug reports did this person submit in the past?

This one could be used to modulate the former question, since if the number of submitted bug reports is really low (like 1), maybe it is not significant to be considered.

@kfogel what do you think?

**Comment by sgoggins** [comment]
@kfogel : We are keenly interested in your thoughts!

**Comment by germonprez** [comment]
@kfogel just checking if you have any comments on this. If nothing in the next few weeks, we're going to close this but happy to open it again at any time.

**Comment by kfogel** [comment]
Hey there!  Please don't close! :-)  Sorry for the delay; I've been meaning to comment, but just had a long winter break followed by a very busy "back at work and catching up" period.  Putting some more thoughts here is on my todo list and I will do so soon.

**Comment by germonprez** [comment]
No problem! :)

**Comment by sgoggins** [comment]
@kfogel : If no movement in the next two weeks we are closing this issue.

**Comment by kfogel** [comment]
My apologies, @sgoggins.  I won't have time to develop this further right now; please go ahead and close.  If I become able to, we can always re-open.

**Comment by jgbarah** [comment]
Thanjs, @sgoggins @kfogel. Closing then.
