### ISSUE TITLE
Update Readme.md headings to match standard for CHAOSS

### ISSUE THREAD

**Issue by sgoggins** [chaoss/wg-evolution#83]
https://docs.google.com/document/d/1pVtYHNTwrGFV3UyiR2qBKV0MvipoEEI-fbwavSNui4Q/edit

Proposed Structure Revision: 

Introduction--Overview (purpose, goal, outcome, process - a sentence each with a link to the full section)
Table of Contents
Background (Problem Statement, Opportunity, Goal, Work to Date)
Key Focuses / Roadmap for 2019 [NOT IN G-M-D]
Metrics / Metrics Focus Areas
Workflow: How to use this repository (Usage) [Added from GMD ReadMe]
Implementations [Added from GMD ReadMe]
Software Work [Not included in GMD ReadMe]
Use Cases [Added from GMD ReadMe]
Related Works [Not included in GMD ReadMe]
Contributing [Moved up in sequence, as compared to GMD ReadMe]
Communications -- Meetings, Mailing List, Discussion Forum [Consolidated, as compared to GMD ReadMe]
Contributors -- Maintainers, Core Contributors
License [Added from GMD ReadMe] (related issue #149)

**Comment by sgoggins** [comment]
Created this issue following discussion in weekly call.

**Comment by jgbarah** [comment]
Can anyone have a look at this one, and maybe produce a pull request? In principle, it is a matter of adding the sections that could be missing, using (when necessary) the file in the D&I working group as a template. In a quick check, it is mainly the section "key focuses/roadmap" (which could just include a link to our roadmap file), and maybe "software work" (not sure about this one).

Before doing the pr, an analysis in a comment to this ticket, about the changes to do (by comparing with the D&I file, and the file linked in the description of this ticket) would be great (so that we can have a preliminary discussion, if needed).

**Comment by harshalmittal4** [comment]
Hey @jgbarah, I will take it and make the PR!

**Comment by GeorgLink** [comment]
D&I has not changed the headings yet. Please find new headings in the
Google doc shared on the mailing list a few weeks ago.

>

**Comment by harshalmittal4** [comment]
@jgbarah, @sgoggins, @GeorgLink, 
Few questions regarding the update:
1) What could be the appropriate content for the **Background** heading for the GMD working group, or shall I just put the heading for now?
2) For the **Roadmap**, **Implementations** and **Use cases** headings, I suppose that I have to include the links to their files. Please correct me if I am wrong.
3) What would comprise the discussion forum if it is to included, in the **Communications** heading.
4) Where can I find the list of maintainers for the **Contributors** heading.

**Comment by GeorgLink** [comment]
> Few questions regarding the update:

Headings without content can be omitted. The goal is a useful README.

**Update:** D&I has an active pull request to update its README structure. 
https://github.com/chaoss/wg-diversity-inclusion/pull/172

**Comment by jgbarah** [comment]
Closing this one, since #132 addresses this (at least for now, i think).

Please feel free to reopen if you think otherwise.
